add install/uninstall script
basherpm/basher pull request #91
Opened 2020-10-19 10:25 UTC by pforret

this PR creates an 'install.sh' script that can be used in a on-line installation step:
curl -s https://raw.githubusercontent.com/basherpm/basher/master/install.sh | bash

to test it now (before merge):
     curl -s https://raw.githubusercontent.com/pforret/basher/master/install.sh | bash
or
     curl -s https://raw.githubusercontent.com/pforret/basher/master/install.sh | zsh

it should work for bash/zsh/sh/fish

there is also an 'uninstall.sh' script that removes basher and basher-related lines in ~/.bashrc/~/.zshrc etc

2021-01-04 09:54 UTC, juanibiapina requested changes

2021-01-04 09:54 UTC, juanibiapina commented on README.md
> +	curl -s https://raw.githubusercontent.com/basherpm/basher/master/install.sh | bash
Could you please add a note somewhere around here clarifying that this will try to update the shell initialization file?

2021-01-05 16:11 UTC, pforret reviewed
like this?

2021-01-24 09:57 UTC, juanibiapina approved these changes

2021-01-24 09:57 UTC, merged

2021-01-24 09:57 UTC, juanibiapina commented
Sorry about the delay.